### PR TITLE
Automatically add session token of currently logged in user to the he…

### PR DESCRIPTION
**Pull request by shannah**
…aders of all command HTTP requests.

### CODE REVIEW

**Comment by sidiabale** [comment]
@shannah: Thanks for the update. Did you also check the tests? I did a quick run and there are some failures. Kindly fix those and add the changes to the pull request.

Cheers

**Comment by shannah** [comment]
Tests were failing out of the box so assumed they weren't kept up.  If I
get time I'll look into your tests to get them working.

**Comment by sidiabale** [comment]
I noticed indeed that some query tests are failing. Strangely it seems to be dependent on the java version. I'll look into that. Your changes required some test updates which I've done myself so you don't need to worry.

BTW: Your patch is missing something, in my opinion: The case when the user is deleted. I've made that change as well.

**Comment by shannah** [comment]
Thanks!

On Tue, Aug 25, 2015 at 8:19 AM, Chidiebere Okwudire <
notifications@github.com> wrote:

> I noticed indeed that some query tests are failing. Strangely it seems to
> be dependent on the java version. I'll look into that. Your changes
> required some test updates which I've done myself so you don't need to
> worry.
>
> BTW: Your patch is missing something, in my opinion: The case when the
> user is deleted. I've made that change as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sidiabale/parse4cn1/pull/4#issuecomment-134620853>.
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by sidiabale** [comment]
Thank YOU!

BTW: I've fixed the failing tests. Can you please confirm that all tests now run successfully?

**Pull request merged**
