### PR TITLE
Master

### PR DESCRIPTION
**Pull request by codenameone**
Minor fix to prevent over verbosity

### CODE REVIEW

**Comment by codenameone** [comment]
Also a bigger fix for long/int getting that might not be the best direction

**Comment by sidiabale** [comment]
Hi Shai,

I don't understand the rationale behind your changes to the getInt() and getLong methods. Can you explain?

**Comment by codenameone** [comment]
I was having an issue with a value returned from parse coming back as double while I was expecting a long.

**Comment by sidiabale** [comment]
I think I get it. At that, I consider this fix only partial. For example, the behavior of getDouble() is now inconsistent with the rest + the method documentation is no longer completely correct. I'll merge your changes and extend it sometime this week

**Pull request merged**
